#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t lazy"

$L "                                       "
$L "               LAZY OS                 "
$L "               BY SHADY                "
$L "                                       "
$L "Welcome to Android `getprop ro.build.version.release` / LazyOS-`getprop ro.lazy.version`";
